(require 'js2-mode)
(add-to-list 'auto-mode-alist '("\\.js\\'" . js2-mode))
(setq js2-mirror-mode t)
(setq js2-enter-indents-newline t)
(setq-default js2-basic-offset 2)
(setq js2-strict-missing-semi-warning nil)
